defmodule EmojiFlags.Data do
  alias EmojiFlags.Flag

  def all do
    [
      %Flag{ iso: "AD",
emoji: "🇦🇩",
unicode: "U+1F1E6 U+1F1E9", name:	"Andorra" },
%Flag{ iso: "AE",
emoji: "🇦🇪",
unicode: "U+1F1E6 U+1F1EA", name:	"United Arab Emirates" },
%Flag{ iso: "AF",
emoji: "🇦🇫",
unicode: "U+1F1E6 U+1F1EB", name:	"Afghanistan" },
%Flag{ iso: "AG",
emoji: "🇦🇬",
unicode: "U+1F1E6 U+1F1EC", name:	"Antigua and Barbuda" },
%Flag{ iso: "AI",
emoji: "🇦🇮",
unicode: "U+1F1E6 U+1F1EE", name:	"Anguilla" },
%Flag{ iso: "AL",
emoji: "🇦🇱",
unicode: "U+1F1E6 U+1F1F1", name:	"Albania" },
%Flag{ iso: "AM",
emoji: "🇦🇲",
unicode: "U+1F1E6 U+1F1F2", name:	"Armenia" },
%Flag{ iso: "AO",
emoji: "🇦🇴",
unicode: "U+1F1E6 U+1F1F4", name:	"Angola" },
%Flag{ iso: "AQ",
emoji: "🇦🇶",
unicode: "U+1F1E6 U+1F1F6", name:	"Antarctica" },
%Flag{ iso: "AR",
emoji: "🇦🇷",
unicode: "U+1F1E6 U+1F1F7", name:	"Argentina" },
%Flag{ iso: "AS",
emoji: "🇦🇸",
unicode: "U+1F1E6 U+1F1F8", name:	"American Samoa" },
%Flag{ iso: "AT",
emoji: "🇦🇹",
unicode: "U+1F1E6 U+1F1F9", name:	"Austria" },
%Flag{ iso: "AU",
emoji: "🇦🇺",
unicode: "U+1F1E6 U+1F1FA", name:	"Australia" },
%Flag{ iso: "AW",
emoji: "🇦🇼",
unicode: "U+1F1E6 U+1F1FC", name:	"Aruba" },
%Flag{ iso: "AX",
emoji: "🇦🇽",
unicode: "U+1F1E6 U+1F1FD", name:	"Åland Islands" },
%Flag{ iso: "AZ",
emoji: "🇦🇿",
unicode: "U+1F1E6 U+1F1FF", name:	"Azerbaijan" },
%Flag{ iso: "BA",
emoji: "🇧🇦",
unicode: "U+1F1E7 U+1F1E6", name:	"Bosnia and Herzegovina" },
%Flag{ iso: "BB",
emoji: "🇧🇧",
unicode: "U+1F1E7 U+1F1E7", name:	"Barbados" },
%Flag{ iso: "BD",
emoji: "🇧🇩",
unicode: "U+1F1E7 U+1F1E9", name:	"Bangladesh" },
%Flag{ iso: "BE",
emoji: "🇧🇪",
unicode: "U+1F1E7 U+1F1EA", name:	"Belgium" },
%Flag{ iso: "BF",
emoji: "🇧🇫",
unicode: "U+1F1E7 U+1F1EB", name:	"Burkina Faso" },
%Flag{ iso: "BG",
emoji: "🇧🇬",
unicode: "U+1F1E7 U+1F1EC", name:	"Bulgaria" },
%Flag{ iso: "BH",
emoji: "🇧🇭",
unicode: "U+1F1E7 U+1F1ED", name:	"Bahrain" },
%Flag{ iso: "BI",
emoji: "🇧🇮",
unicode: "U+1F1E7 U+1F1EE", name:	"Burundi" },
%Flag{ iso: "BJ",
emoji: "🇧🇯",
unicode: "U+1F1E7 U+1F1EF", name:	"Benin" },
%Flag{ iso: "BL",
emoji: "🇧🇱",
unicode: "U+1F1E7 U+1F1F1", name:	"Saint Barthélemy" },
%Flag{ iso: "BM",
emoji: "🇧🇲",
unicode: "U+1F1E7 U+1F1F2", name:	"Bermuda" },
%Flag{ iso: "BN",
emoji: "🇧🇳",
unicode: "U+1F1E7 U+1F1F3", name:	"Brunei Darussalam" },
%Flag{ iso: "BO",
emoji: "🇧🇴",
unicode: "U+1F1E7 U+1F1F4", name:	"Bolivia" },
%Flag{ iso: "BQ",
emoji: "🇧🇶",
unicode: "U+1F1E7 U+1F1F6", name:	"Bonaire, Sint Eustatius and Saba" },
%Flag{ iso: "BR",
emoji: "🇧🇷",
unicode: "U+1F1E7 U+1F1F7", name:	"Brazil" },
%Flag{ iso: "BS",
emoji: "🇧🇸",
unicode: "U+1F1E7 U+1F1F8", name:	"Bahamas" },
%Flag{ iso: "BT",
emoji: "🇧🇹",
unicode: "U+1F1E7 U+1F1F9", name:	"Bhutan" },
%Flag{ iso: "BV",
emoji: "🇧🇻",
unicode: "U+1F1E7 U+1F1FB", name:	"Bouvet Island" },
%Flag{ iso: "BW",
emoji: "🇧🇼",
unicode: "U+1F1E7 U+1F1FC", name:	"Botswana" },
%Flag{ iso: "BY",
emoji: "🇧🇾",
unicode: "U+1F1E7 U+1F1FE", name:	"Belarus" },
%Flag{ iso: "BZ",
emoji: "🇧🇿",
unicode: "U+1F1E7 U+1F1FF", name:	"Belize" },
%Flag{ iso: "CA",
emoji: "🇨🇦",
unicode: "U+1F1E8 U+1F1E6", name:	"Canada" },
%Flag{ iso: "CC",
emoji: "🇨🇨",
unicode: "U+1F1E8 U+1F1E8", name:	"Cocos (Keeling) Islands" },
%Flag{ iso: "CD",
emoji: "🇨🇩",
unicode: "U+1F1E8 U+1F1E9", name:	"Congo" },
%Flag{ iso: "CF",
emoji: "🇨🇫",
unicode: "U+1F1E8 U+1F1EB", name:	"Central African Republic" },
%Flag{ iso: "CG",
emoji: "🇨🇬",
unicode: "U+1F1E8 U+1F1EC", name:	"Congo" },
%Flag{ iso: "CH",
emoji: "🇨🇭",
unicode: "U+1F1E8 U+1F1ED", name:	"Switzerland" },
%Flag{ iso: "CI",
emoji: "🇨🇮",
unicode: "U+1F1E8 U+1F1EE", name:	"Côte D'Ivoire" },
%Flag{ iso: "CK",
emoji: "🇨🇰",
unicode: "U+1F1E8 U+1F1F0", name:	"Cook Islands" },
%Flag{ iso: "CL",
emoji: "🇨🇱",
unicode: "U+1F1E8 U+1F1F1", name:	"Chile" },
%Flag{ iso: "CM",
emoji: "🇨🇲",
unicode: "U+1F1E8 U+1F1F2", name:	"Cameroon" },
%Flag{ iso: "CN",
emoji: "🇨🇳",
unicode: "U+1F1E8 U+1F1F3", name:	"China" },
%Flag{ iso: "CO",
emoji: "🇨🇴",
unicode: "U+1F1E8 U+1F1F4", name:	"Colombia" },
%Flag{ iso: "CR",
emoji: "🇨🇷",
unicode: "U+1F1E8 U+1F1F7", name:	"Costa Rica" },
%Flag{ iso: "CU",
emoji: "🇨🇺",
unicode: "U+1F1E8 U+1F1FA", name:	"Cuba" },
%Flag{ iso: "CV",
emoji: "🇨🇻",
unicode: "U+1F1E8 U+1F1FB", name:	"Cape Verde" },
%Flag{ iso: "CW",
emoji: "🇨🇼",
unicode: "U+1F1E8 U+1F1FC", name:	"Curaçao" },
%Flag{ iso: "CX",
emoji: "🇨🇽",
unicode: "U+1F1E8 U+1F1FD", name:	"Christmas Island" },
%Flag{ iso: "CY",
emoji: "🇨🇾",
unicode: "U+1F1E8 U+1F1FE", name:	"Cyprus" },
%Flag{ iso: "CZ",
emoji: "🇨🇿",
unicode: "U+1F1E8 U+1F1FF", name:	"Czech Republic" },
%Flag{ iso: "DE",
emoji: "🇩🇪",
unicode: "U+1F1E9 U+1F1EA", name:	"Germany" },
%Flag{ iso: "DJ",
emoji: "🇩🇯",
unicode: "U+1F1E9 U+1F1EF", name:	"Djibouti" },
%Flag{ iso: "DK",
emoji: "🇩🇰",
unicode: "U+1F1E9 U+1F1F0", name:	"Denmark" },
%Flag{ iso: "DM",
emoji: "🇩🇲",
unicode: "U+1F1E9 U+1F1F2", name:	"Dominica" },
%Flag{ iso: "DO",
emoji: "🇩🇴",
unicode: "U+1F1E9 U+1F1F4", name:	"Dominican Republic" },
%Flag{ iso: "DZ",
emoji: "🇩🇿",
unicode: "U+1F1E9 U+1F1FF", name:	"Algeria" },
%Flag{ iso: "EC",
emoji: "🇪🇨",
unicode: "U+1F1EA U+1F1E8", name:	"Ecuador" },
%Flag{ iso: "EE",
emoji: "🇪🇪",
unicode: "U+1F1EA U+1F1EA", name:	"Estonia" },
%Flag{ iso: "EG",
emoji: "🇪🇬",
unicode: "U+1F1EA U+1F1EC", name:	"Egypt" },
%Flag{ iso: "EH",
emoji: "🇪🇭",
unicode: "U+1F1EA U+1F1ED", name:	"Western Sahara" },
%Flag{ iso: "ER",
emoji: "🇪🇷",
unicode: "U+1F1EA U+1F1F7", name:	"Eritrea" },
%Flag{ iso: "ES",
emoji: "🇪🇸",
unicode: "U+1F1EA U+1F1F8", name:	"Spain" },
%Flag{ iso: "ET",
emoji: "🇪🇹",
unicode: "U+1F1EA U+1F1F9", name:	"Ethiopia" },
%Flag{ iso: "FI",
emoji: "🇫🇮",
unicode: "U+1F1EB U+1F1EE", name:	"Finland" },
%Flag{ iso: "FJ",
emoji: "🇫🇯",
unicode: "U+1F1EB U+1F1EF", name:	"Fiji" },
%Flag{ iso: "FK",
emoji: "🇫🇰",
unicode: "U+1F1EB U+1F1F0", name:	"Falkland Islands (Malvinas)" },
%Flag{ iso: "FM",
emoji: "🇫🇲",
unicode: "U+1F1EB U+1F1F2", name:	"Micronesia" },
%Flag{ iso: "FO",
emoji: "🇫🇴",
unicode: "U+1F1EB U+1F1F4", name:	"Faroe Islands" },
%Flag{ iso: "FR",
emoji: "🇫🇷",
unicode: "U+1F1EB U+1F1F7", name:	"France" },
%Flag{ iso: "GA",
emoji: "🇬🇦",
unicode: "U+1F1EC U+1F1E6", name:	"Gabon" },
%Flag{ iso: "GB",
emoji: "🇬🇧",
unicode: "U+1F1EC U+1F1E7", name:	"United Kingdom" },
%Flag{ iso: "GD",
emoji: "🇬🇩",
unicode: "U+1F1EC U+1F1E9", name:	"Grenada" },
%Flag{ iso: "GE",
emoji: "🇬🇪",
unicode: "U+1F1EC U+1F1EA", name:	"Georgia" },
%Flag{ iso: "GF",
emoji: "🇬🇫",
unicode: "U+1F1EC U+1F1EB", name:	"French Guiana" },
%Flag{ iso: "GG",
emoji: "🇬🇬",
unicode: "U+1F1EC U+1F1EC", name:	"Guernsey" },
%Flag{ iso: "GH",
emoji: "🇬🇭",
unicode: "U+1F1EC U+1F1ED", name:	"Ghana" },
%Flag{ iso: "GI",
emoji: "🇬🇮",
unicode: "U+1F1EC U+1F1EE", name:	"Gibraltar" },
%Flag{ iso: "GL",
emoji: "🇬🇱",
unicode: "U+1F1EC U+1F1F1", name:	"Greenland" },
%Flag{ iso: "GM",
emoji: "🇬🇲",
unicode: "U+1F1EC U+1F1F2", name:	"Gambia" },
%Flag{ iso: "GN",
emoji: "🇬🇳",
unicode: "U+1F1EC U+1F1F3", name:	"Guinea" },
%Flag{ iso: "GP",
emoji: "🇬🇵",
unicode: "U+1F1EC U+1F1F5", name:	"Guadeloupe" },
%Flag{ iso: "GQ",
emoji: "🇬🇶",
unicode: "U+1F1EC U+1F1F6", name:	"Equatorial Guinea" },
%Flag{ iso: "GR",
emoji: "🇬🇷",
unicode: "U+1F1EC U+1F1F7", name:	"Greece" },
%Flag{ iso: "GS",
emoji: "🇬🇸",
unicode: "U+1F1EC U+1F1F8", name:	"South Georgia" },
%Flag{ iso: "GT",
emoji: "🇬🇹",
unicode: "U+1F1EC U+1F1F9", name:	"Guatemala" },
%Flag{ iso: "GU",
emoji: "🇬🇺",
unicode: "U+1F1EC U+1F1FA", name:	"Guam" },
%Flag{ iso: "GW",
emoji: "🇬🇼",
unicode: "U+1F1EC U+1F1FC", name:	"Guinea-Bissau" },
%Flag{ iso: "GY",
emoji: "🇬🇾",
unicode: "U+1F1EC U+1F1FE", name:	"Guyana" },
%Flag{ iso: "HK",
emoji: "🇭🇰",
unicode: "U+1F1ED U+1F1F0", name:	"Hong Kong" },
%Flag{ iso: "HM",
emoji: "🇭🇲",
unicode: "U+1F1ED U+1F1F2", name:	"Heard Island and Mcdonald Islands" },
%Flag{ iso: "HN",
emoji: "🇭🇳",
unicode: "U+1F1ED U+1F1F3", name:	"Honduras" },
%Flag{ iso: "HR",
emoji: "🇭🇷",
unicode: "U+1F1ED U+1F1F7", name:	"Croatia" },
%Flag{ iso: "HT",
emoji: "🇭🇹",
unicode: "U+1F1ED U+1F1F9", name:	"Haiti" },
%Flag{ iso: "HU",
emoji: "🇭🇺",
unicode: "U+1F1ED U+1F1FA", name:	"Hungary" },
%Flag{ iso: "ID",
emoji: "🇮🇩",
unicode: "U+1F1EE U+1F1E9", name:	"Indonesia" },
%Flag{ iso: "IE",
emoji: "🇮🇪",
unicode: "U+1F1EE U+1F1EA", name:	"Ireland" },
%Flag{ iso: "IL",
emoji: "🇮🇱",
unicode: "U+1F1EE U+1F1F1", name:	"Israel" },
%Flag{ iso: "IM",
emoji: "🇮🇲",
unicode: "U+1F1EE U+1F1F2", name:	"Isle of Man" },
%Flag{ iso: "IN",
emoji: "🇮🇳",
unicode: "U+1F1EE U+1F1F3", name:	"India" },
%Flag{ iso: "IO",
emoji: "🇮🇴",
unicode: "U+1F1EE U+1F1F4", name:	"British Indian Ocean Territory" },
%Flag{ iso: "IQ",
emoji: "🇮🇶",
unicode: "U+1F1EE U+1F1F6", name:	"Iraq" },
%Flag{ iso: "IR",
emoji: "🇮🇷",
unicode: "U+1F1EE U+1F1F7", name:	"Iran" },
%Flag{ iso: "IS",
emoji: "🇮🇸",
unicode: "U+1F1EE U+1F1F8", name:	"Iceland" },
%Flag{ iso: "IT",
emoji: "🇮🇹",
unicode: "U+1F1EE U+1F1F9", name:	"Italy" },
%Flag{ iso: "JE",
emoji: "🇯🇪",
unicode: "U+1F1EF U+1F1EA", name:	"Jersey" },
%Flag{ iso: "JM",
emoji: "🇯🇲",
unicode: "U+1F1EF U+1F1F2", name:	"Jamaica" },
%Flag{ iso: "JO",
emoji: "🇯🇴",
unicode: "U+1F1EF U+1F1F4", name:	"Jordan" },
%Flag{ iso: "JP",
emoji: "🇯🇵",
unicode: "U+1F1EF U+1F1F5", name:	"Japan" },
%Flag{ iso: "KE",
emoji: "🇰🇪",
unicode: "U+1F1F0 U+1F1EA", name:	"Kenya" },
%Flag{ iso: "KG",
emoji: "🇰🇬",
unicode: "U+1F1F0 U+1F1EC", name:	"Kyrgyzstan" },
%Flag{ iso: "KH",
emoji: "🇰🇭",
unicode: "U+1F1F0 U+1F1ED", name:	"Cambodia" },
%Flag{ iso: "KI",
emoji: "🇰🇮",
unicode: "U+1F1F0 U+1F1EE", name:	"Kiribati" },
%Flag{ iso: "KM",
emoji: "🇰🇲",
unicode: "U+1F1F0 U+1F1F2", name:	"Comoros" },
%Flag{ iso: "KN",
emoji: "🇰🇳",
unicode: "U+1F1F0 U+1F1F3", name:	"Saint Kitts and Nevis" },
%Flag{ iso: "KP",
emoji: "🇰🇵",
unicode: "U+1F1F0 U+1F1F5", name:	"North Korea" },
%Flag{ iso: "KR",
emoji: "🇰🇷",
unicode: "U+1F1F0 U+1F1F7", name:	"South Korea" },
%Flag{ iso: "KW",
emoji: "🇰🇼",
unicode: "U+1F1F0 U+1F1FC", name:	"Kuwait" },
%Flag{ iso: "KY",
emoji: "🇰🇾",
unicode: "U+1F1F0 U+1F1FE", name:	"Cayman Islands" },
%Flag{ iso: "KZ",
emoji: "🇰🇿",
unicode: "U+1F1F0 U+1F1FF", name:	"Kazakhstan" },
%Flag{ iso: "LA",
emoji: "🇱🇦",
unicode: "U+1F1F1 U+1F1E6", name:	"Lao People's Democratic Republic" },
%Flag{ iso: "LB",
emoji: "🇱🇧",
unicode: "U+1F1F1 U+1F1E7", name:	"Lebanon" },
%Flag{ iso: "LC",
emoji: "🇱🇨",
unicode: "U+1F1F1 U+1F1E8", name:	"Saint Lucia" },
%Flag{ iso: "LI",
emoji: "🇱🇮",
unicode: "U+1F1F1 U+1F1EE", name:	"Liechtenstein" },
%Flag{ iso: "LK",
emoji: "🇱🇰",
unicode: "U+1F1F1 U+1F1F0", name:	"Sri Lanka" },
%Flag{ iso: "LR",
emoji: "🇱🇷",
unicode: "U+1F1F1 U+1F1F7", name:	"Liberia" },
%Flag{ iso: "LS",
emoji: "🇱🇸",
unicode: "U+1F1F1 U+1F1F8", name:	"Lesotho" },
%Flag{ iso: "LT",
emoji: "🇱🇹",
unicode: "U+1F1F1 U+1F1F9", name:	"Lithuania" },
%Flag{ iso: "LU",
emoji: "🇱🇺",
unicode: "U+1F1F1 U+1F1FA", name:	"Luxembourg" },
%Flag{ iso: "LV",
emoji: "🇱🇻",
unicode: "U+1F1F1 U+1F1FB", name:	"Latvia" },
%Flag{ iso: "LY",
emoji: "🇱🇾",
unicode: "U+1F1F1 U+1F1FE", name:	"Libya" },
%Flag{ iso: "MA",
emoji: "🇲🇦",
unicode: "U+1F1F2 U+1F1E6", name:	"Morocco" },
%Flag{ iso: "MC",
emoji: "🇲🇨",
unicode: "U+1F1F2 U+1F1E8", name:	"Monaco" },
%Flag{ iso: "MD",
emoji: "🇲🇩",
unicode: "U+1F1F2 U+1F1E9", name:	"Moldova" },
%Flag{ iso: "ME",
emoji: "🇲🇪",
unicode: "U+1F1F2 U+1F1EA", name:	"Montenegro" },
%Flag{ iso: "MF",
emoji: "🇲🇫",
unicode: "U+1F1F2 U+1F1EB", name:	"Saint Martin (French Part)" },
%Flag{ iso: "MG",
emoji: "🇲🇬",
unicode: "U+1F1F2 U+1F1EC", name:	"Madagascar" },
%Flag{ iso: "MH",
emoji: "🇲🇭",
unicode: "U+1F1F2 U+1F1ED", name:	"Marshall Islands" },
%Flag{ iso: "MK",
emoji: "🇲🇰",
unicode: "U+1F1F2 U+1F1F0", name:	"Macedonia" },
%Flag{ iso: "ML",
emoji: "🇲🇱",
unicode: "U+1F1F2 U+1F1F1", name:	"Mali" },
%Flag{ iso: "MM",
emoji: "🇲🇲",
unicode: "U+1F1F2 U+1F1F2", name:	"Myanmar" },
%Flag{ iso: "MN",
emoji: "🇲🇳",
unicode: "U+1F1F2 U+1F1F3", name:	"Mongolia" },
%Flag{ iso: "MO",
emoji: "🇲🇴",
unicode: "U+1F1F2 U+1F1F4", name:	"Macao" },
%Flag{ iso: "MP",
emoji: "🇲🇵",
unicode: "U+1F1F2 U+1F1F5", name:	"Northern Mariana Islands" },
%Flag{ iso: "MQ",
emoji: "🇲🇶",
unicode: "U+1F1F2 U+1F1F6", name:	"Martinique" },
%Flag{ iso: "MR",
emoji: "🇲🇷",
unicode: "U+1F1F2 U+1F1F7", name:	"Mauritania" },
%Flag{ iso: "MS",
emoji: "🇲🇸",
unicode: "U+1F1F2 U+1F1F8", name:	"Montserrat" },
%Flag{ iso: "MT",
emoji: "🇲🇹",
unicode: "U+1F1F2 U+1F1F9", name:	"Malta" },
%Flag{ iso: "MU",
emoji: "🇲🇺",
unicode: "U+1F1F2 U+1F1FA", name:	"Mauritius" },
%Flag{ iso: "MV",
emoji: "🇲🇻",
unicode: "U+1F1F2 U+1F1FB", name:	"Maldives" },
%Flag{ iso: "MW",
emoji: "🇲🇼",
unicode: "U+1F1F2 U+1F1FC", name:	"Malawi" },
%Flag{ iso: "MX",
emoji: "🇲🇽",
unicode: "U+1F1F2 U+1F1FD", name:	"Mexico" },
%Flag{ iso: "MY",
emoji: "🇲🇾",
unicode: "U+1F1F2 U+1F1FE", name:	"Malaysia" },
%Flag{ iso: "MZ",
emoji: "🇲🇿",
unicode: "U+1F1F2 U+1F1FF", name:	"Mozambique" },
%Flag{ iso: "NA",
emoji: "🇳🇦",
unicode: "U+1F1F3 U+1F1E6", name:	"Namibia" },
%Flag{ iso: "NC",
emoji: "🇳🇨",
unicode: "U+1F1F3 U+1F1E8", name:	"New Caledonia" },
%Flag{ iso: "NE",
emoji: "🇳🇪",
unicode: "U+1F1F3 U+1F1EA", name:	"Niger" },
%Flag{ iso: "NF",
emoji: "🇳🇫",
unicode: "U+1F1F3 U+1F1EB", name:	"Norfolk Island" },
%Flag{ iso: "NG",
emoji: "🇳🇬",
unicode: "U+1F1F3 U+1F1EC", name:	"Nigeria" },
%Flag{ iso: "NI",
emoji: "🇳🇮",
unicode: "U+1F1F3 U+1F1EE", name:	"Nicaragua" },
%Flag{ iso: "NL",
emoji: "🇳🇱",
unicode: "U+1F1F3 U+1F1F1", name:	"Netherlands" },
%Flag{ iso: "NO",
emoji: "🇳🇴",
unicode: "U+1F1F3 U+1F1F4", name:	"Norway" },
%Flag{ iso: "NP",
emoji: "🇳🇵",
unicode: "U+1F1F3 U+1F1F5", name:	"Nepal" },
%Flag{ iso: "NR",
emoji: "🇳🇷",
unicode: "U+1F1F3 U+1F1F7", name:	"Nauru" },
%Flag{ iso: "NU",
emoji: "🇳🇺",
unicode: "U+1F1F3 U+1F1FA", name:	"Niue" },
%Flag{ iso: "NZ",
emoji: "🇳🇿",
unicode: "U+1F1F3 U+1F1FF", name:	"New Zealand" },
%Flag{ iso: "OM",
emoji: "🇴🇲",
unicode: "U+1F1F4 U+1F1F2", name:	"Oman" },
%Flag{ iso: "PA",
emoji: "🇵🇦",
unicode: "U+1F1F5 U+1F1E6", name:	"Panama" },
%Flag{ iso: "PE",
emoji: "🇵🇪",
unicode: "U+1F1F5 U+1F1EA", name:	"Peru" },
%Flag{ iso: "PF",
emoji: "🇵🇫",
unicode: "U+1F1F5 U+1F1EB", name:	"French Polynesia" },
%Flag{ iso: "PG",
emoji: "🇵🇬",
unicode: "U+1F1F5 U+1F1EC", name:	"Papua New Guinea" },
%Flag{ iso: "PH",
emoji: "🇵🇭",
unicode: "U+1F1F5 U+1F1ED", name:	"Philippines" },
%Flag{ iso: "PK",
emoji: "🇵🇰",
unicode: "U+1F1F5 U+1F1F0", name:	"Pakistan" },
%Flag{ iso: "PL",
emoji: "🇵🇱",
unicode: "U+1F1F5 U+1F1F1", name:	"Poland" },
%Flag{ iso: "PM",
emoji: "🇵🇲",
unicode: "U+1F1F5 U+1F1F2", name:	"Saint Pierre and Miquelon" },
%Flag{ iso: "PN",
emoji: "🇵🇳",
unicode: "U+1F1F5 U+1F1F3", name:	"Pitcairn" },
%Flag{ iso: "PR",
emoji: "🇵🇷",
unicode: "U+1F1F5 U+1F1F7", name:	"Puerto Rico" },
%Flag{ iso: "PS",
emoji: "🇵🇸",
unicode: "U+1F1F5 U+1F1F8", name:	"Palestinian Territory" },
%Flag{ iso: "PT",
emoji: "🇵🇹",
unicode: "U+1F1F5 U+1F1F9", name:	"Portugal" },
%Flag{ iso: "PW",
emoji: "🇵🇼",
unicode: "U+1F1F5 U+1F1FC", name:	"Palau" },
%Flag{ iso: "PY",
emoji: "🇵🇾",
unicode: "U+1F1F5 U+1F1FE", name:	"Paraguay" },
%Flag{ iso: "QA",
emoji: "🇶🇦",
unicode: "U+1F1F6 U+1F1E6", name:	"Qatar" },
%Flag{ iso: "RE",
emoji: "🇷🇪",
unicode: "U+1F1F7 U+1F1EA", name:	"Réunion" },
%Flag{ iso: "RO",
emoji: "🇷🇴",
unicode: "U+1F1F7 U+1F1F4", name:	"Romania" },
%Flag{ iso: "RS",
emoji: "🇷🇸",
unicode: "U+1F1F7 U+1F1F8", name:	"Serbia" },
%Flag{ iso: "RU",
emoji: "🇷🇺",
unicode: "U+1F1F7 U+1F1FA", name:	"Russia" },
%Flag{ iso: "RW",
emoji: "🇷🇼",
unicode: "U+1F1F7 U+1F1FC", name:	"Rwanda" },
%Flag{ iso: "SA",
emoji: "🇸🇦",
unicode: "U+1F1F8 U+1F1E6", name:	"Saudi Arabia" },
%Flag{ iso: "SB",
emoji: "🇸🇧",
unicode: "U+1F1F8 U+1F1E7", name:	"Solomon Islands" },
%Flag{ iso: "SC",
emoji: "🇸🇨",
unicode: "U+1F1F8 U+1F1E8", name:	"Seychelles" },
%Flag{ iso: "SD",
emoji: "🇸🇩",
unicode: "U+1F1F8 U+1F1E9", name:	"Sudan" },
%Flag{ iso: "SE",
emoji: "🇸🇪",
unicode: "U+1F1F8 U+1F1EA", name:	"Sweden" },
%Flag{ iso: "SG",
emoji: "🇸🇬",
unicode: "U+1F1F8 U+1F1EC", name:	"Singapore" },
%Flag{ iso: "SH",
emoji: "🇸🇭",
unicode: "U+1F1F8 U+1F1ED", name:	"Saint Helena, Ascension and Tristan Da Cunha" },
%Flag{ iso: "SI",
emoji: "🇸🇮",
unicode: "U+1F1F8 U+1F1EE", name:	"Slovenia" },
%Flag{ iso: "SJ",
emoji: "🇸🇯",
unicode: "U+1F1F8 U+1F1EF", name:	"Svalbard and Jan Mayen" },
%Flag{ iso: "SK",
emoji: "🇸🇰",
unicode: "U+1F1F8 U+1F1F0", name:	"Slovakia" },
%Flag{ iso: "SL",
emoji: "🇸🇱",
unicode: "U+1F1F8 U+1F1F1", name:	"Sierra Leone" },
%Flag{ iso: "SM",
emoji: "🇸🇲",
unicode: "U+1F1F8 U+1F1F2", name:	"San Marino" },
%Flag{ iso: "SN",
emoji: "🇸🇳",
unicode: "U+1F1F8 U+1F1F3", name:	"Senegal" },
%Flag{ iso: "SO",
emoji: "🇸🇴",
unicode: "U+1F1F8 U+1F1F4", name:	"Somalia" },
%Flag{ iso: "SR",
emoji: "🇸🇷",
unicode: "U+1F1F8 U+1F1F7", name:	"Suriname" },
%Flag{ iso: "SS",
emoji: "🇸🇸",
unicode: "U+1F1F8 U+1F1F8", name:	"South Sudan" },
%Flag{ iso: "ST",
emoji: "🇸🇹",
unicode: "U+1F1F8 U+1F1F9", name:	"Sao Tome and Principe" },
%Flag{ iso: "SV",
emoji: "🇸🇻",
unicode: "U+1F1F8 U+1F1FB", name:	"El Salvador" },
%Flag{ iso: "SX",
emoji: "🇸🇽",
unicode: "U+1F1F8 U+1F1FD", name:	"Sint Maarten (Dutch Part)" },
%Flag{ iso: "SY",
emoji: "🇸🇾",
unicode: "U+1F1F8 U+1F1FE", name:	"Syrian Arab Republic" },
%Flag{ iso: "SZ",
emoji: "🇸🇿",
unicode: "U+1F1F8 U+1F1FF", name:	"Swaziland" },
%Flag{ iso: "TC",
emoji: "🇹🇨",
unicode: "U+1F1F9 U+1F1E8", name:	"Turks and Caicos Islands" },
%Flag{ iso: "TD",
emoji: "🇹🇩",
unicode: "U+1F1F9 U+1F1E9", name:	"Chad" },
%Flag{ iso: "TF",
emoji: "🇹🇫",
unicode: "U+1F1F9 U+1F1EB", name:	"French Southern Territories" },
%Flag{ iso: "TG",
emoji: "🇹🇬",
unicode: "U+1F1F9 U+1F1EC", name:	"Togo" },
%Flag{ iso: "TH",
emoji: "🇹🇭",
unicode: "U+1F1F9 U+1F1ED", name:	"Thailand" },
%Flag{ iso: "TJ",
emoji: "🇹🇯",
unicode: "U+1F1F9 U+1F1EF", name:	"Tajikistan" },
%Flag{ iso: "TK",
emoji: "🇹🇰",
unicode: "U+1F1F9 U+1F1F0", name:	"Tokelau" },
%Flag{ iso: "TL",
emoji: "🇹🇱",
unicode: "U+1F1F9 U+1F1F1", name:	"Timor-Leste" },
%Flag{ iso: "TM",
emoji: "🇹🇲",
unicode: "U+1F1F9 U+1F1F2", name:	"Turkmenistan" },
%Flag{ iso: "TN",
emoji: "🇹🇳",
unicode: "U+1F1F9 U+1F1F3", name:	"Tunisia" },
%Flag{ iso: "TO",
emoji: "🇹🇴",
unicode: "U+1F1F9 U+1F1F4", name:	"Tonga" },
%Flag{ iso: "TR",
emoji: "🇹🇷",
unicode: "U+1F1F9 U+1F1F7", name:	"Turkey" },
%Flag{ iso: "TT",
emoji: "🇹🇹",
unicode: "U+1F1F9 U+1F1F9", name:	"Trinidad and Tobago" },
%Flag{ iso: "TV",
emoji: "🇹🇻",
unicode: "U+1F1F9 U+1F1FB", name:	"Tuvalu" },
%Flag{ iso: "TW",
emoji: "🇹🇼",
unicode: "U+1F1F9 U+1F1FC", name:	"Taiwan" },
%Flag{ iso: "TZ",
emoji: "🇹🇿",
unicode: "U+1F1F9 U+1F1FF", name:	"Tanzania" },
%Flag{ iso: "UA",
emoji: "🇺🇦",
unicode: "U+1F1FA U+1F1E6", name:	"Ukraine" },
%Flag{ iso: "UG",
emoji: "🇺🇬",
unicode: "U+1F1FA U+1F1EC", name:	"Uganda" },
%Flag{ iso: "UM",
emoji: "🇺🇲",
unicode: "U+1F1FA U+1F1F2", name:	"United States Minor Outlying Islands" },
%Flag{ iso: "US",
emoji: "🇺🇸",
unicode: "U+1F1FA U+1F1F8", name:	"United States" },
%Flag{ iso: "UY",
emoji: "🇺🇾",
unicode: "U+1F1FA U+1F1FE", name:	"Uruguay" },
%Flag{ iso: "UZ",
emoji: "🇺🇿",
unicode: "U+1F1FA U+1F1FF", name:	"Uzbekistan" },
%Flag{ iso: "VA",
emoji: "🇻🇦",
unicode: "U+1F1FB U+1F1E6", name:	"Vatican City" },
%Flag{ iso: "VC",
emoji: "🇻🇨",
unicode: "U+1F1FB U+1F1E8", name:	"Saint Vincent and The Grenadines" },
%Flag{ iso: "VE",
emoji: "🇻🇪",
unicode: "U+1F1FB U+1F1EA", name:	"Venezuela" },
%Flag{ iso: "VG",
emoji: "🇻🇬",
unicode: "U+1F1FB U+1F1EC", name:	"Virgin Islands, British" },
%Flag{ iso: "VI",
emoji: "🇻🇮",
unicode: "U+1F1FB U+1F1EE", name:	"Virgin Islands, U.S." },
%Flag{ iso: "VN",
emoji: "🇻🇳",
unicode: "U+1F1FB U+1F1F3", name:	"Viet Nam" },
%Flag{ iso: "VU",
emoji: "🇻🇺",
unicode: "U+1F1FB U+1F1FA", name:	"Vanuatu" },
%Flag{ iso: "WF",
emoji: "🇼🇫",
unicode: "U+1F1FC U+1F1EB", name:	"Wallis and Futuna" },
%Flag{ iso: "WS",
emoji: "🇼🇸",
unicode: "U+1F1FC U+1F1F8", name:	"Samoa" },
%Flag{ iso: "YE",
emoji: "🇾🇪",
unicode: "U+1F1FE U+1F1EA", name:	"Yemen" },
%Flag{ iso: "YT",
emoji: "🇾🇹",
unicode: "U+1F1FE U+1F1F9", name:	"Mayotte" },
%Flag{ iso: "ZA",
emoji: "🇿🇦",
unicode: "U+1F1FF U+1F1E6", name:	"South Africa" },
%Flag{ iso: "ZM",
emoji: "🇿🇲",
unicode: "U+1F1FF U+1F1F2", name:	"Zambia" },
%Flag{ iso: "ZW",
emoji: "🇿🇼",
unicode: "U+1F1FF U+1F1FC", name:	"Zimbabwe" },
    ]
  end
end
